export * from "./login";
export * from "./menu";
export * from "./signup";
export * from "./homePage";
export * from "./mapDelivery";
export * from "./forgotpassword";
export * from "./terms";
export * from "./securityTerms";
export * from "./order";
